name: CI Pipeline

on:
  push:
  release:
    types: [released]

jobs:
  ci-pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
          settings-path: ${{ github.workspace }}

#      - name: Set up Maven
#        uses: whelk-io/maven-settings-xml-action@v2
#        with:
#          repositories: '[{ "id": "github-ccaoa", "url": "https://maven.pkg.github.com/ccaoa/maven-repo" }]'
#          servers: '[{ "id": "treklee-github", "username": "treklee-bot", "password": "${{ secrets.MVN_REPO_TOKEN }}" }]'

      - name: Build
        if: github.event_name != 'release'
        run: mvn -B install -DskipTests

      - name: Build & publish to Maven repo
        if: github.event_name == 'release'
        run: mvn -B deploy -DskipTests
